version: "2"

run:
  timeout: 2m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - errorlint
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - prealloc
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
